name: IRIS Homework CI

# Triggers
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:  # manual trigger if needed

permissions:
  contents: write
  pull-requests: write


jobs:
  test_model:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.2"

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - uses: iterative/setup-cml@v2

    - name: Authenticate to Google Cloud & Pull DVC data
      env:
        GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
      run: |
        echo "$GCP_CREDENTIALS_JSON" > key.json
        export GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        dvc pull iris_feast/iris_model.bin.dvc

    - name: Start MLflow server (optional for testing)
      run: |
        mlflow server --backend-store-uri sqlite:///mlflow.db \
                      --default-artifact-root ./mlruns \
                      --host 127.0.0.1 --port 8100 &
        sleep 20  # wait for server to start
    - name: Run unit tests
      env:
        MLFLOW_TRACKING_URI: http://127.0.0.1:8100
      run: |
        cd iris_feast && python -m test 2>&1 | tee test_output.txt

    - name: Create CML report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "### Test Output" > report.md
        echo "\`\`\`" >> report.md
        cat iris_feast/test_output.txt >> report.md
        echo "\`\`\`" >> report.md
        echo "### Metrics from training" >> report.md
        if [ -f iris_feast/metrics.csv ]; then cat iris_feast/metrics.csv >> report.md; fi
        cml comment create --publish report.md

